### ISSUE TITLE
Can't add new page template

### ISSUE THREAD

**Issue by kaplan512** [SimonPadbury/b4st#30] opened 2017-11-23 21:29 UTC
Hi, good theme, but I have some problem
I create new page template page-about.php and write this 
```
<?php
/*
Template Name: About
*/
?>
```
but I can't choose template for pages, I don't even have this drop down list in my admin panel.
Can you help me?
Thank you

**Comment by SimonPadbury** [comment] 2017-11-23 21:39
Hi, yes I can help. 

But it’s late for me today. I will try to help tomorrow or Saturday. 

Simon

**Comment by kaplan512** [comment] 2017-11-23 21:46
Ok, I hope you will answer asap :-)
I did this https://stackoverflow.com/questions/3987773/template-dropdown-not-showing-up-within-wordpress-administrator-page but it didn`t help

**Comment by kaplan512** [comment] 2017-11-23 22:15
I found a solution. I just remove you last comment from style.css

**Comment by SimonPadbury** [comment] 2017-11-24 07:14
Hi Kaplan,

You said,

> I found a solution. I just remove you last comment from style.css

I don't understand why you needed to do that. I don't need to do that.

---

I just did this, and it works OK:

(1.) Create a duplicate of the existing `page.php`. Give it your chosen filename: `page-about.php`. This template must be in the theme root folder, beside `page.php`.

* You may wish to immediately modify the template, so that it is obviously different to `page.php` -- only to test it. E.g. add a Bootstrap `alert` in a prominent place. 

(2.) At the top of your `page-about.php`, add your chosen Template Name:

```
<?php
/*
Template Name: About
*/
?>
```

(3.) Start a new **Page** and you will see your **About** template in the dropdown. It should just work.

You should now be able to change its layout, CSS classes, widget areas, any way you like.

---

Here is my example `page-about.php` that I just has success with:

```
<?php
/*
Template Name: About (Custom Page)
*/
?>

<?php get_header(); ?>

<div class="container mt-4 alert alert-success">
  If you can see this, then you are using the template <code>page-about.php</code>.
</div>

<div class="container">
  <div class="row">

    <div class="<?php if(is_active_sidebar('sidebar-widget-area')): ?>col-sm-8<?php else: ?>col-sm-12<?php endif; ?>">
      <div id="content" role="main">
        <?php get_template_part('loops/content', 'page'); ?>
      </div><!-- /#content -->
    </div>

    <div class="col-sm-4" id="sidebar" role="navigation">
       <?php get_sidebar(); ?>
    </div>

  </div><!-- /.row -->
</div><!-- /.container -->

<?php get_footer(); ?>
```

**Comment by kaplan512** [comment] 2017-11-24 12:16
I don't know, I did the same, but id didn't work, so I just remove the additional comment from style.css and it helped

**Comment by kaplan512** [comment] 2017-11-24 12:37
Oh no. I add only 2 additional templates and that`s all, I can't add more... I don't understand

**Comment by kaplan512** [comment] 2017-11-24 13:13
I don't  know why, but I should add new description to style.css and it is still do not work appropriate

**Comment by ricardo-vargas** [comment] 2017-11-24 17:24
I had to do the same to solve it, change the description of the theme on style.css, I have not tested thoroughly with new tempaltes but I will comment if any new issue comes up.

**Comment by SimonPadbury** [comment] 2017-11-24 18:30
Hi guys,

Are you saying that this comment in `styles.css` is breaking the theme?

```
/*
Do not put your styles in here - put them in `theme/css/b4st.css`.
*/
```

I have never known this to break the theme before. I don't know why it has started breaking the theme now. And on my local server, this comment is not causing me any problem.

Anyway, I just deleted it from `styles.css` -- and I added a note in `README.md` about not putting your styles in there.

**Closed** 2017-12-25 08:26 UTC
